### ISSUE TITLE
Scan freeze and PHP fread() error

### ISSUE THREAD

**Issue by adefaria** [z000ao8q/audios#571]
This problem is similar to issue #385 with a different line number.

Ran docker exec -itu 33 nextcloud php occ audioplayer:scan admin --all -v. Log files attached. 

1. Reset library
2. Ran docker exec -itu 33 nextcloud php occ audioplayer:scan admin --all -v
3. See error

**Expected behavior**
Run to completion 

**Versions:**
 - Nextcloud: 23.0.0
 - Audioplayer 3.2.4

**Nextcloud log**
[audioplayer_scan.log](https://github.com/Rello/audioplayer/files/8240437/audioplayer_scan.log)
[nextcloud.log](https://github.com/Rello/audioplayer/files/8240441/nextcloud.log)

**Comment by gr3k** [comment]
Hello, I have this same issue.
I have tried to scan my music library today.

docker exec --user www-data nextcloud-app /var/www/html/occ audioplayer:scan -vvv grek

Nextcloud version: 23.0.2
Audioplayer:  3.2.4

[audioplayer.log](https://github.com/Rello/audioplayer/files/8282626/audioplayer.log)

**Comment by gr3k** [comment]
Hey.
It looks like I found a solution.
So generally updating file: getid3.php resolved my problem.
It was fixed in https://github.com/JamesHeinrich/getID3/commit/6f7b917e01992bc4720a90f244254873f9aa86a9
The solution is very simple. Update 3rd party getid3 from their github ;) 

Audioplayer using: 
1.9.20-202109010614
1.9.21-202111201212 -at this version problem has been fixed.

**Comment by Rello** [comment]
Hello,
thank you for your support here.
I will check and do some tests. then I can push the update shortly.
thank you

**Comment by Rello** [comment]
3.3.0 released
